config/routes.rb
Rails.application.routes.draw do

  get 'components/new'

  get 'components/new'

  get 'ingredients/new'

  devise_for :users
  resources :kegs
  resources :flavors do
    resources :components
  end
  resources :batches
  resources :ingredients

  root 'kegs#index'

end

app/models/flavor.rb
class Flavor < ActiveRecord::Base

  has_many :components
  has_many :ingredients, through: :components

  scope :batch_eligible, -> {joins(:components).having('SUM(percentage) = 100').group('flavors.id')}

  validates :name, presence: true, uniqueness: {case_sensitive: false, message: "This flavor name is already in the system"}, format:{with: /\A[a-zA-z\s]{6,}\z/, message: "The flavor name must be at least 6 characters (with no numbers)"}
  validates :abbreviation, presence: true, uniqueness: {message: "This abbreviation is already in use"}, format:{with: /\A[A-Z]{4}\z/, message: "The flavor abbreviation MUST BE four letters only"}
  with_options if: Proc.new { |a| !a.gpg.nil?}, on: [:create, :update] do |flavor|
    flavor.validates :gpg, numericality: {message: "The grams per gallon must be a number greater than 60"}
    flavor.validates :gpg, numericality: {greater_than_or_equal_to: 60, message: "The grams per gallon must be at least 60"}
    flavor.validates :gpg, numericality: {less_than_or_equal_to: 500, message: "The grams per gallon must be a number no greater than 500"}

  end

  def abbreviation=(value)
    write_attribute(:abbreviation, value.upcase)
  end

  def destroy
    self.update_attributes(archive: true)
  end

  def batch_eligible?
    self.components.sum('percentage') == 100 && !(self.gpg.nil?)
  end


  
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController

  before_action :get_flavor, only: [:show, :edit, :destroy, :update]

  def index
    @flavors = Flavor.all
  end
  def new
    @flavor = Flavor.new
  end

  def create
    @flavor = Flavor.new(flavor_params)
    if @flavor.save
      flash[:success] = "Flavor has been added"
      redirect_to @flavor
    else
      flash.now[:warning] = "The flavor was not created"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @flavor.update_attributes(flavor_params)
      flash[:success] = "The flavor was updated"
      redirect_to @flavor
    else
      flash[:warning] = "The flavor was not updated"
      render 'edit'
    end
  end

  def destroy
    @flavor.destroy
    flash[:success] = "#{@flavor.name} has been successfully archived"
    redirect_to flavors_path
  end

  private

  def flavor_params
    params.require(:flavor).permit(:name, :abbreviation, :gpg)
  end

  def get_flavor
    @flavor = Flavor.find(params[:id])
  end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.erb
<% if flavor.errors.any? %>
	<%= render 'layouts/errors', object: flavor %>
<% end %>
<%= form_for(flavor) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :abbreviation %>
  <%= f.text_field :abbreviation %>

  <%= f.label :gpg, "Default Grams per Gallon" %>
  <%= f.number_field :gpg %>

  <%= f.submit %>
<% end %>

app/views/flavors/edit.html.erb
<%= render 'form', flavor: @flavor %>

app/views/flavors/index.html.erb
<% @flavors.each do |f| %>
  <%= div_for f  do %>
    <%= f.name %>
    <%= link_to "Flavor Detail", flavor_path(f) %>
    <%= link_to "Archive Flavor", flavor_path(f), method: :delete, data: {confirm: "Are you sure you want to archive this flavor"} %>
  <% end %>
<% end %>

app/views/flavors/new.html.erb
<%= render 'form', flavor: @flavor %>

app/views/flavors/show.html.erb
<div class="header">
	<%= @flavor.name %>
</div>

<%= @flavor.abbreviation %>

<%= link_to "Edit Flavor", edit_flavor_path(@flavor) %>

<%= link_to "Add Component", new_flavor_component_path(@flavor) %>

<% if @flavor.batch_eligible? %>
	<%= link_to "Create Batch From #{@flavor.name}", new_batch_path(flavor: @flavor.id) %>
	<%= link_to "Create FULL Batch from #{@flavor.name}", new_batch_path(flavor: @flavor.id, gallons: 42) %>
<% else %>
	<span class="warning">Batches of this flavor can not be made until the both the recipe is set and the grams per gallon is entered</span>
<% end %>

<% if !@flavor.components.empty? %>
	<div class="components">
	<% @flavor.components.each do |comp| %>
		<%= div_for(comp) do %>
			<%= comp.ingredient.name %>
			<%= comp.percentage %>
			<%= link_to "Edit Ingredient", edit_flavor_component_path(@flavor, comp) %>
		<% end %>
	<% end %>
	</div>
<% end %>