config/routes.rb
Rails.application.routes.draw do

  get 'components/new'

  get 'components/new'

  get 'ingredients/new'

  devise_for :users
  resources :kegs
  resources :flavors do
    resources :components
  end
  resources :batches
  resources :ingredients

  root 'kegs#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

	has_many :components
	has_many :flavors, through: :components

  validates :name, presence: true, uniqueness: { case_sensitive: false, message: "This ingredient is already in the database" }, length: { minimum: 4 }

  def destroy
  	if self.flavors.any?
  		self.update(archived: true)
  	else
  		super
  	end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :get_ingredient, only: [:edit, :update, :show, :destroy]

  def index
    @ingredients = Ingredient.all
  end
  
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "The ingredient has been added"
      redirect_to @ingredient
    else
      flash.now[:warning] = "The ingredient was not added"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ingredient.update_attributes(ingredient_params)
      flash[:success] = "Ingredient was updated"
      redirect_to @ingredient
    else
      flash.now[:warning] = "Ingredient was not updated"
      render 'edit'
    end
  end

  def destroy
    @ingredient.destroy
    if Ingredient.find_by(id: params[:id])
      flash[:warning] = "The ingredient has been archived, it could not be deleted"
      redirect_to @ingredient
    else
      flash[:success] = "The ingredient was deleted" 
      redirect_to ingredients_path
    end
  end

  private

    def ingredient_params
      params.require(:ingredient).permit(:name)
    end

    def get_ingredient
      @ingredient = Ingredient.find(params[:id])
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<% if ingredient.errors.any? %>
  <% ingredient.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>
<%= form_for(ingredient) do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "#{method} Ingredient" %>
<% end %>

app/views/ingredients/edit.html.erb
<%= render 'form', {ingredient: @ingredient, method: "Update"} %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<% @ingredients.each do |ingredient| %>
	<div class="row">
		<%= div_for(ingredient) do %>
			<%= link_to ingredient.name, ingredient_path(ingredient) %>
		<% end %>
	</div>
<% end %>

app/views/ingredients/new.html.erb
<%= render 'form', {ingredient: @ingredient, method: "Add"} %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>
<% if @ingredient.archived? %>
	<span id="archived">ARCHIVED</span>
<% end %>

<%= link_to "Edit #{@ingredient.name}", edit_ingredient_path(@ingredient) %>
<%= link_to "Delete #{@ingredient.name}", ingredient_path(@ingredient), method: :delete, data: {confirm: "Are you sure you want to delete this ingredient?"} %>

<% if @ingredient.flavors.any? %>
	<h3 id="component_usage">
		<%= @ingredient.name.capitalize %> is used in the following flavors
	</h3>
	<% @ingredient.flavors.each do |flavor| %>
		<%= div_for(flavor) do %>
			<%= link_to flavor.name, flavor_path(flavor) %>
		<% end %>
	<% end %>
<% end %>