config/routes.rb
Rails.application.routes.draw do

  get 'components/new'

  get 'components/new'

  get 'ingredients/new'

  devise_for :users
  resources :kegs
  resources :flavors do
    resources :components
  end
  resources :batches
  resources :ingredients

  root 'kegs#index'

end

app/models/keg.rb
class Keg < ActiveRecord::Base

  validates :serial_number, presence: true, uniqueness: {message: "This serial number is already in use with another keg."}, format: {with: /\A[0-9]{2}-[0-9]{6}B\z/, message: "Please use a properly formatted serial number"}

  default_scope { where('status != 6')}

  enum status: [:empty, :filled, :priming, :ready, :consigned, :returned, :retired]
  
  def destroy
    self.update_attributes(status: 6)
  end
end

app/controllers/kegs_controller.rb
class KegsController < ApplicationController

  before_action :find_keg, only: [:show, :edit, :update, :destroy]

  def new
    @keg = Keg.new
  end

  def create
    @keg = Keg.new(keg_params)
    if @keg.save
      flash[:success] = "Keg has been added"
      redirect_to @keg
    else
      flash.now[:warning] = "The keg was not added"
      render 'new'
    end
  end

  def index
    @kegs = Keg.all
  end

  def show
  end

  def edit
  end

  def update
    if @keg.update(keg_params)
      flash[:success] = "The keg was updated successfully"
      redirect_to @keg
    else
      flash.now[:warning] = "The keg was not updated"
      render 'edit'
    end
  end

  def destroy
    @keg.destroy
    flash[:success] = "The keg was retired"
    redirect_to kegs_path
  end


  private

    def keg_params
      params.require(:keg).permit(:serial_number)
    end

    def find_keg
      @keg = Keg.find(params[:id])
    end
end

app/helpers/kegs_helper.rb
module KegsHelper
end

app/views/kegs/_form.html.erb
<% if keg.errors.any? %>
  <%= render 'layouts/errors', object: keg %>
<% end %>
<%= form_for(keg) do |f| %>

  <%= f.label :serial_number %>
  <%= f.text_field :serial_number %>

  <%= f.submit %>

<% end %>

app/views/kegs/edit.html.erb
<%= render 'form', keg: @keg %>

app/views/kegs/index.html.erb
<% @kegs.each do |keg| %>
  <%= link_to keg.serial_number, keg_path(keg) %>
<% end %>

app/views/kegs/new.html.erb
<%= render 'form', keg: @keg %>

app/views/kegs/show.html.erb
<%= @keg.serial_number %>

<div class="status">
  Status: <%= @keg.status.capitalize %>
</div>

<div class="location" >
  Location: <%= @keg.location %>
</div>
<%= link_to "Edit Keg", edit_keg_path(@keg) %>
<%= link_to "Retire Keg", keg_path(@keg), method: :delete, data: {confirm: "Are you sure you want to retire this keg?"} %>