config/routes.rb
Rails.application.routes.draw do

  get 'components/new'

  get 'components/new'

  get 'ingredients/new'

  devise_for :users
  resources :kegs
  resources :flavors do
    resources :components
  end
  resources :batches
  resources :ingredients

  root 'kegs#index'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :flavor
  has_many :components, through: :flavor
  before_create :check_batch_eligiblity
  after_create :set_lot, :set_bestby

  validates :gallons, presence: true, numericality: {greater_than_or_equal_to: 10, less_than_or_equal_to: 42}
  validates :flavor_id, presence: true

  enum status: [:pending, :in_progress, :priming, :completed]

  def best_by
    super.strftime("%m/%d/%y")
  end

  private

    def set_lot
      x = Batch.where(flavor_id: flavor_id, created_at: Time.now.midnight..(Time.now.midnight + 1.day)).count - 1
      y = ("A".."Z").to_a[x]
      self.update_attributes(lot: "#{self.flavor.abbreviation}-#{self.created_at.strftime("%m%d%y")}-#{y}")
    end

    def set_bestby
      self.update_attributes(best_by: self.created_at + 120.days)
    end

    def check_batch_eligiblity
      self.flavor.batch_eligible?
    end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController

  before_action :get_batch, only: [:edit, :show, :update, :destroy]

  def index
    @batches = Batch.all
  end

  def new
    if params[:flavor]
      if params[:gallons]
        @batch = Batch.create(flavor_id: params[:flavor], gallons: params[:gallons])
        flash[:success] = "The batch was created"
        redirect_to @batch
      else
        @batch = Batch.new(flavor_id: params[:flavor])
      end
    else
      @batch = Batch.new
    end
  end

  def create 
    @batch = Batch.new(batch_params)

   if  @batch.save
      flash[:success] = "The batch was created"
      redirect_to @batch
    else
      flash[:warning] = "The batch was not created"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if !(@batch.flavor_id == params[:batch][:flavor_id])
      @batch.lot[0..3] = Flavor.find(params[:batch][:flavor_id]).abbreviation
    end
    if @batch.update_attributes(batch_params)
      flash[:success] = "The batch has been updated"
      redirect_to @batch
    else
      flash[:warning] = "The batch was not changed"
      render 'edit'
    end
  end

  def destroy
    @batch.destroy
    flash[:success] = "The batch has been deleted"
    redirect_to root_path
  end



  private

    def batch_params
      params.require(:batch).permit(:flavor_id, :gallons)
    end

    def get_batch
      @batch = Batch.find(params[:id])
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<% if batch.errors.any? %>
  <% batch.errors.full_messages.each do |msg| %>
    <p>
      <%= msg %>
    </p>
  <% end %>
<% end %>

<%= form_for(batch) do |f| %>
  
  <%= f.label :flavor %>
  <% if !batch.flavor_id.nil? %>
    <%= f.collection_select(:flavor_id, Flavor.batch_eligible, :id, :name, selected: batch.flavor_id) %>
  <% else %>
    <%= f.collection_select(:flavor_id, Flavor.batch_eligible, :id, :name, prompt: true) %>
  <% end %>

  <%= f.label :gallons %>
  <%= f.number_field :gallons %>

  <%= f.submit "#{action} Batch" %>
<% end %>

app/views/batches/edit.html.erb
<%= render 'form', {batch: @batch, action: "Update"}%>

app/views/batches/index.html.erb
<h1>Batches</h1>

<% @batches.each do |batch| %>
	<%= div_for(batch) do %>
		<%= link_to batch.lot, batch_path(batch) %>
		<%= batch.flavor.name %>
	<% end %>
<% end %>

app/views/batches/new.html.erb
<%= render 'form', {batch: @batch, action: "Create"}%>

app/views/batches/show.html.erb
<%= @batch.flavor.name %>
<%= @batch.lot %>
<div id="gallons">
	<%= @batch.gallons %>
</div>

Best By Date: <%= @batch.best_by %>
<div id="status">
	Status: <%= @batch.status.capitalize %>
</div>
<%=link_to "Edit Batch", edit_batch_path(@batch) %>
<%= link_to "Delete Batch", batch_path(@batch), method: :delete, data: {confirm: "Are you sure you want to delete this batch?"} %>
<div id="components">
	<% @batch.components.each do |component| %>
		<%= div_for(component.ingredient) do %>
			<%= component.ingredient.name %>
			<%= component.percentage * @batch.gallons * @batch.flavor.gpg %>
		<% end %>
	<% end %>
</div>